### ISSUE TITLE
Optimization missing, appointed by the Google Page Speed.

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/layouts#52]
I love the Spark theme,
but I was doing a test on the Google page speed, and realized that it is not very optimized.
![35it4ox](https://cloud.githubusercontent.com/assets/5193643/11363716/c106ecae-9282-11e5-9d6c-e82db548cabb.png)

Both for mobile and for desktop.
![2n0sr4h](https://cloud.githubusercontent.com/assets/5193643/11363726/ccfe9e08-9282-11e5-923a-da1f50b98108.png)

The same is not happening with the river and others.
![np3y4j](https://cloud.githubusercontent.com/assets/5193643/11363738/dad99906-9282-11e5-990d-f1ed02debf1f.png)
![2yjsb3p](https://cloud.githubusercontent.com/assets/5193643/11363743/df2ebbc6-9282-11e5-81af-908bbd28326f.png)

I intend to purchase a commercial license, I hope in future updates this issue is solved! :)

**Comment by jamaltun** [comment]
Hi,
Thanks for your opinions.

The reason for this situation , we use image maps on the dashboard . These images are slow to load because they are large SVG images . When you delete images you will get a better score because it is for demonstration purposes .
In our next edition we will reduce the size of these images.

**Comment by diegoarantes** [comment]
Hello, thanks,
I had not thought about it , I Realized it was really the SVG images because when i put on the blank page example, got a higher score.
